export const RECEIVE_GET_MOVIES = 'RECEIVE_GET_MOVIES';
export const RECEIVE_GET_MOVIE = 'RECEIVE_GET_MOVIE';
export const RECEIVE_GET_CAST = 'RECEIVE_GET_CAST';
export const RECEIVE_GET_SEARCH_MOVIES = 'RECEIVE_GET_SEARCH_MOVIES';

export const VIEW_PRODUCTS = 'VIEW_PRODUCTS';